<a href="https://colab.research.google.com/github/anuhya901-cell/cesppl-internship/blob/main/w2_numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

create a 5x5 array of random integers between 0 and 100; find its row means, column means, and overall maximum; replace every value below 50 with 0; reshape it into a 1x25 array.

In [1]:
import numpy as np

# Create a 5x5 array of random integers from 0 to 100
arr = np.random.randint(0, 101, size=(5, 5))

print("Original Array:")
print(arr)

# Row means
row_means = np.mean(arr, axis=1)
print("\nRow Means:")
print(row_means)

# Column means
col_means = np.mean(arr, axis=0)
print("\nColumn Means:")
print(col_means)

# Overall maximum
overall_max = np.max(arr)
print("\nOverall Maximum:")
print(overall_max)

# Replace values below 50 with 0
modified_arr = arr.copy()
modified_arr[modified_arr < 50] = 0

print("\nModified Array:")
print(modified_arr)

# Reshape into 1x25 array
reshaped_arr = modified_arr.reshape(1, 25)

print("\nReshaped Array:")
print(reshaped_arr)

Original Array:
[[63 77 71 96 46]
 [90 34 56 85 17]
 [45 11 43 99 20]
 [59 88 14 19 18]
 [87 66 56 22 36]]

Row Means:
[70.6 56.4 43.6 39.6 53.4]

Column Means:
[68.8 55.2 48.  64.2 27.4]

Overall Maximum:
99

Modified Array:
[[63 77 71 96  0]
 [90  0 56 85  0]
 [ 0  0  0 99  0]
 [59 88  0  0  0]
 [87 66 56  0  0]]

Reshaped Array:
[[63 77 71 96  0 90  0 56 85  0  0  0  0 99  0 59 88  0  0  0 87 66 56  0
   0]]


Write a function that takes a 224 by 224 by 3 NumPy array (we will treat it as an RGB image) and returns a grayscale version using the weighted formula 0.299R + 0.587G + 0.114B. Test it on a random array of shape (224, 224, 3).

RGB to Grayscale Function

Formula:

0.299R+0.587G+0.114B

In [2]:
import numpy as np

def rgb_to_grayscale(image):
    """
    Converts RGB image to grayscale.
    image shape: (224, 224, 3)
    """

    r = image[:, :, 0]
    g = image[:, :, 1]
    b = image[:, :, 2]

    grayscale = 0.299 * r + 0.587 * g + 0.114 * b

    return grayscale

# Test with random image
random_image = np.random.randint(
    0, 256,
    size=(224, 224, 3),
    dtype=np.uint8
)

gray_image = rgb_to_grayscale(random_image)

print("Original Shape:", random_image.shape)
print("Grayscale Shape:", gray_image.shape)

Original Shape: (224, 224, 3)
Grayscale Shape: (224, 224)


Write a function that takes the same array and returns it horizontally flipped, without using np.flip. The slicing trick is array[:, ::-1, :].

Horizontal Flip Function

In [3]:
def horizontal_flip(image):
    """
    Horizontally flips image without np.flip
    """

    return image[:, ::-1, :]

# Test
flipped_image = horizontal_flip(random_image)

print("Flipped Shape:", flipped_image.shape)

Flipped Shape: (224, 224, 3)


Normalize and Denormalize Image

In [4]:
def normalize_image(image):
    """
    Converts uint8 image (0-255)
    to float image (0-1)
    """

    return image.astype(np.float32) / 255.0

Write a function that normalizes a uint8 image array (values 0 to 255) to float values between 0 and 1. Then write its inverse.

Inverse Function

In [6]:
def denormalize_image(image):
    """
    Converts float image (0-1)
    back to uint8 image (0-255)
    """

    return (image * 255).astype(np.uint8)

Test

In [7]:
normalized = normalize_image(random_image)

print("Normalized Min:", normalized.min())
print("Normalized Max:", normalized.max())

restored = denormalize_image(normalized)

print("Restored dtype:", restored.dtype)

Normalized Min: 0.0
Normalized Max: 1.0
Restored dtype: uint8
